// Generated by CoffeeScript 1.3.3
(function() {
  var attrs,
    __slice = [].slice;

  attrs = function() {
    var ctor, names;
    ctor = arguments[0], names = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    return names.forEach(function(name) {
      return Object.defineProperty(ctor.prototype, name, {
        get: function() {
          return this.get(name);
        },
        set: function(val) {
          return this.set(name, val);
        },
        enumerable: true,
        configurable: true
      });
    });
  };

  attrs.install = function(target) {
    if (target == null) {
      target = require('backbone' + '').Model;
    }
    return target.attrs = function() {
      var names;
      names = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return attrs.apply(null, [this].concat(__slice.call(names)));
    };
  };

  module.exports = attrs;

}).call(this);
